name: WarpGUI
version: '0.1'
main: mc.aayush262.WarpGUI
api-version: '1.21'
authors: [aayush262]
depend: [Essentials]
description: A warp GUI for EssentialsX
website: https://github.com/aayush2622
commands:
  warpgui:
    aliases:
      - wg
      - warps
    description: Open the warps GUI
    usage: /warpgui <warpName>